# Generated by Django 4.0.4 on 2022-05-27 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista_servico', models.CharField(choices=[('1', 'Tatuagem'), ('2', 'Corte de Cabelo')], max_length=1, verbose_name='Lista de serviços')),
                ('valor_servico', models.DecimalField(decimal_places=2, default='', max_digits=7, verbose_name='Valor do serviço')),
                ('data_servico', models.DateTimeField(verbose_name='Data do serviço')),
                ('marcar_servico', models.BooleanField(default=True)),
                ('modo_pagamento', models.BooleanField(default=False, verbose_name='Cartão de crédito')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
        ),
    ]
